# -*- mode: org -*-
#+STARTUP: indent hidestars showall

* load-file
This is a series of attempts at highlight.js on a local file.
** test2.html
file:./load-file/test2.html
- Trying to load with XMLHttpRequest()
- This fundamentally doesn't work because this is intended to load a
  file from the server side
- One way to make it work is with a local server
- Chrome plug in webserver Web Server for Chrome
- npm http_server
** test3.html
- Stripped highlight.js part and focused on loading, no errors on
  loading the page

* dynamic-insertion
This deals with adding elements to web page, in order to break down
the potential problem of load-file.
** test4.html
- someElement.insertAdjacentHTML(<position>,<text-added>)
** test5.html
- dynamic insertion within a function
- Added window.onLoad function
** test6.html
- more dynamic adding ing +=
* multi-mode
The main reason I explored the above two sections is to have emacs
deal with language specific code in a separate file, and have that
filed added to the html containing the highlight.js for
fontification.

But if there is a way to edit in the html code, then I don't need to
create a separate file and to someone automatically include it.

** test7.html
- working version with python code included, with multi-web-mode
  looking at # --python-start-- : this is the trigger to use python
  mode and can be set from within .emacs when editin html files
- this was successful but it doesn't quite feel the same environment
  on this little section
